name: bhagwad_gita
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  extra_lints:
    git: https://github.com/mitulvaghamshi/extra_lints.git

flutter:
  uses-material-design: true

  assets:
    - assets/gita_reflections_en.json
    - assets/gita_reflections_hi.json
    - assets/gita_snippets_en.json
    - assets/gita_snippets_hi.json
    - assets/gita.json
