name: wiki_search
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0
  http: ^1.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/wiki.json
