name: hello_world
description: An absolute bare-bones web app.
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.6
  lints: ^6.0.0
