name: Build and deploy to pages

on:
  #push:
  #  branches: ["main"]

  # Run only when triggered manually.
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  main:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Minify Html source
        shell: sh
        run: sh ../.github/workflows/minify.sh
        working-directory: www

      - name: Configure GitHub pages
        uses: actions/configure-pages@v5.0.0

      - name: Upload GitHub pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: 'www'

      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
