name: Build and deploy to pages
on:
  #push:
  #  branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Minify
        run: |
          cat dankawala/index.html | while read line; do echo -n "$line" >> dankawala/temp.html; done;
          mv -f dankawala/temp.html dankawala/index.html
          cat tailormade/index.html | while read line; do echo -n "$line" >> tailormade/temp.html; done;
          mv -f tailormade/temp.html tailormade/index.html
          cat index.html | while read line; do echo -n "$line" >> temp.html; done;
          mv -f temp.html index.html
          cat policy.html | while read line; do echo -n "$line" >> temp.html; done;
          mv -f temp.html policy.html
        working-directory: www
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5.0.0
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: 'www'
        id: deployment
